language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  - CONDA_DEPS="numpy scipy nose pip scikit-learn"
  - PIP_DEPS="supersmoother astroML astroML_addons"

install:
  - conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes $CONDA_DEPS
  - pip install $PIP_DEPS
  - python setup.py install

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # miniconda is not always up-to-date with conda.
  - conda update --yes conda

script:
  - nosetests --with-doctest gatspy
